---

# Specify the .NET package to install:
#   Runtime: aspnetcore-runtime-2.1
#   SDK: dotnet-sdk-2.1

dotnet_pkg:
  - "aspnetcore-runtime-{{ backend_dotnet_version | default('3.1') }}"

deprecated_pkgs:
  - aspnetcore-runtime-2.1
  - dotnet-runtime-2.1
  - dotnet-hostfxr-2.1
  - dotnet-runtime-deps-2.1

#dotnet_pkg: dotnet-sdk-2.1
