---


#############################
# installation file locations
www_uploads_dir: /var/thecombine/uploads
www_uploads_owner: www-data
www_uploads_group: www-data

www_app_dir: "/var/www/{{ ansible_fqdn }}/htdocs"
www_app_owner: www-data
www_app_group: www-data

combine_backend_dir: /home/combine/Backend

#############################
# setup logging
combine_log_directory: /var/log
combine_log_file:  combine.log
combine_program_id: CombineBackend


#############################
# environment variables for service
combine_backend_env_vars:
  ASPNETCORE_ENVIRONMENT: Production
  DOTNET_PRINT_TELEMETRY_MESSAGE: false
