---

######################################
# This role sets up the NUC to use
# the Let's Encrypt certificate from
# thecombine.languagetechnology.org
# and to automatically update its
# copy from the server when connected
# to the network
######################################

- name: create letsencrypt directory
  file:
    path: /etc/letsencrypt
    state: directory
    owner: root
    group: root
    mode: 0755

- name: get certs from thecombine.languagetechnology.org
  command: "{{ cert_sync_command }}"

- name: install cert sync script
  template:
    src: sync_cert.sh.j2
    dest: /usr/local/bin/sync_cert.sh
    owner: root
    group: root
    mode: 0750
  notify: Restart sync_cert

- name: install packages for cert sync service
  apt:
    name:
      - dateutils
    state: present

- name: Create service directory
  file:
    path: /usr/lib/systemd/system
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create logging file for Synchronizine the Certificate
  file:
    path: "{{ cert_sync_log_directory }}/{{ cert_sync_log_file }}"
    state: touch
    owner: syslog
    group: adm
    mode: 0640
  notify: Restart rsyslog

- name: Setup rsyslog to log to separate file
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.d/40-cert_sync.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart rsyslog

- name: install cert sync service
  template:
    src: sync_cert.service.j2
    dest: /usr/lib/systemd/system/sync_cert.service
    owner: root
    group: root
    mode:  0644
  notify: Restart sync_cert

- name: start sync_cert service
  systemd:
    name: sync_cert
    daemon_reload: yes
    enabled: yes
    state: started

- name: install support scripts
  copy:
    src: relink_cert
    dest: /usr/local/bin/relink_cert
    owner: root
    group: root
    mode: 0755

- name: install script to check certificate on demand
  template:
    src: trigger_cert_sync.j2
    dest: /usr/local/bin/trigger_cert_sync
    owner: root
    group: root
    mode: 0755

- name: Trigger certificate check when wired ethernet is connected
  file:
    src: "/usr/local/bin/trigger_cert_sync"
    dest: "/usr/lib/networkd-dispatcher/routable.d/10-trigger_cert_sync"
    state: link
    owner: root
    group: root
    mode: 0755
