---

- name: Create service directory
  file:
    path: /usr/lib/systemd/system
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create logging file for Combine Backend
  file:
    path: "{{ combine_log_directory }}/{{ combine_log_file }}"
    state: touch
    owner: "{{ combine_log_owner }}"
    group: "{{ combine_log_group }}"
    mode: 0640
  notify: Restart rsyslog

- name: Setup rsyslog to log to separate file
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.d/30-combinebackend.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart rsyslog

- name: Setup log rotation
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/combine
    owner: root
    group: root
    mode: 0644

- name: install backend service file
  template:
    src: combine_backend.service.j2
    dest: /usr/lib/systemd/system/combine_backend.service
    owner: root
    group: root
    mode: 0644
  notify: Restart combine_backend

- name: Start combine_backend
  systemd:
    name: combine_backend
    daemon_reload: yes
    enabled: yes
    state: started
