---
##############################################################
# Playbook: playbook_kube_install.yml
#
# playbook_kube_install.yml installs the packages and
# configuration files that are required to run TheCombine
# as Docker containers managed by a Kubernetes cluster.
#
##############################################################

- name: Configure hardware for The Combine
  hosts: all
  gather_facts: yes
  become: yes

  vars_files:
    - "vars/config_common.yml"
    - "vars/packages.yml"

  tasks:
    - name: Update packages
      apt:
        update_cache: yes
        upgrade: "yes"

    - name: Setup WiFi Access Point
      import_role:
        name: wifi_ap
      when: has_wifi

    - name: Configure Network Interfaces
      import_role:
        name: network_config

    - name: Install Docker Subsystem
      import_role:
        name: docker_install

    - name: Install Kubernetes Tools
      import_role:
        name: k8s_install
