---

- name: Fix grub timeout for LVM
  copy:
    src: grub.defaults
    dest: /etc/default/grub
    owner: root
    group: root
    mode:  0644
  register: grubdefaults

- name: Commit new grub config
  command: update-grub
  when: grubdefaults.changed

###################################################################
#
# The following tasks are needed if we decide to install GNOME on
# the server or if we decide to use Ubuntu Desktop.  These changes
# will allow the user to shutdown the device by pressing the power
# button - the device will shutdown without requiring any user
# interaction.
#
#- name: Set chassis to vm
#  shell: hostnamectl set-chassis vm
#  tags: desktop
#
#- name: Install psutil
#  pip:
#    name: psutil
#  tags: desktop
#
#- name: Install dconf configuration tool
#  apt:
#    name: dconf-cli
#  tags: desktop
#
#- name: Configure power button
#  dconf:
#    key: "/org/gnome/settings-daemon/plugins/power/button-power"
#    value: "shutdown"
#    state: present
