---
################################################
# Group specific configuration items
#
# Group: server
################################################

################################################
# Configure Kubernetes cluster
################################################

image_pull_secret: aws-login-credentials
use_airgap_images: False

create_namespaces: []
# k8s namespaces
app_namespace: thecombine

################################################
# Support Tool Settings
################################################
install_ip_viewer: False
install_combinectl: False

#######################################
# Ingress configuration
ingress_namespace: ingress-nginx

################################################
# WiFi access point settings
################################################
has_wifi: False

################################################
# hardware monitoring settings
################################################
include_hw_monitoring: False
