---
#######################################
# Persistent storage size configurations
backend_data_size: 4Gi
database_data_size: 2Gi

# Backend configuration
combine_password_reset_time: 15
combine_smtp_address: no-reply@thecombine.app
combine_smtp_from: "The Combine"
combine_smtp_port: 587
combine_smtp_server: "email-smtp.us-east-1.amazonaws.com"

#######################################
# Default configs for development
config_captcha_required: true
config_captcha_sitekey: "6Le6BL0UAAAAAMjSs1nINeB5hqDZ4m3mMg3k67x3"

#######################################
# environment variable overrides
# for non-development deployments
combine_backend_env_vars:

combine_pull_images: true
combine_image_backend: combine_backend
combine_image_frontend: combine_frontend
combine_image_maintenance: combine_maint

#######################################
# Environment variable defaults for the
# certmgr
cert_issuer: letsencrypt-prod

#######################################
# Ingress configuration
ingress_class: nginx
ingress_namespace: ingress-nginx

#######################################
# Default Backup Schedule
# Run every day at 03:15 UTC
combine_backup_schedule: "15 03 * * *"
